version: "3"
services:
  iris:
    image: intersystemsdc/iris-community:2024.1-preview
    ports:
      - 6272:1972
      - 6273:52773
    environment:
      - IRISUSERNAME=test
      - IRISPASSWORD=test
      - IRISNAMESPACE=TEST
    working_dir: /home/irisowner/llama-iris
    volumes:
      - ./:/home/irisowner/llama-iris
